name: Auto approve dependabot PRs

on:
  pull_request_target:

permissions:
  pull-requests: write

jobs:
  autoapprove:
    name: Auto-Approve a PR by dependabot
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]'
    steps:
      - name: Auto approve
        uses: cognitedata/auto-approve-dependabot-action@v3.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
